#ifndef _RP2040_EXPLORATION_RETURN_VALUES
#define _RP2040_EXPLORATION_RETURN_VALUES



enum rp2040_exploration_return_values
{
    ROUTINE_OK = 0,

// related to module "readings set":
    RS_ACCELEROMETER_READINGS_SET_FILLED,
    RS_ACCELEROMETER_READINGS_SET_FILLED_PARTLY,
    RS_ACCELEROMETER_READINGS_SET_EMPTY,
    RS_ACCELEROMETER_READINGS_SET_NOT_READY,
    RS_STORE_READINGS_CALLED_BUT_NONE_WRITTEN,

    COUNT_OF_RETURN_VALUES
};



#endif // _RP2040_EXPLORATION_RETURN_VALUES
