#ifndef _RP2040_EXPLORE__DEVELOPMENT_DEFINES
#define _RP2040_EXPLORE__DEVELOPMENT_DEFINES



#define DEV_0805_KEEP_BLINKY_CODE_ENABLED
//#define DEV_0808__BLINK_FROM_MAIN_NOT_FROM_THREAD
#define DEV_0805__WS2812_BRING_UP_WORK_ON_RP2040


// Defines to support vRMS math testing without CLI, scoreboard module and
// app conversions header file:

//#define DEV_0808__SCOREBOARD_AVAILABLE

#define VRMS_POWER_OF_TEN_SCALING_FOR_JSON (10000)

#define FULL_READINGS_SET (2048)

#define SIZE_OF_160_BYTES (160)
#define SIZE_OF_MESSAGE_SHORT SIZE_OF_160_BYTES

// To support vRMS code testing:
#define PULSE_DEV__VRMS_SHOW_RAW_DATA_BUFFER
#define RP2040_STUDY_SIMULATE_AXIS_X_READINGS
#define RP2040_STUDY_SHOW_VRMS_SUMMARY
#define RP2040_STUDY_PRINTF_FLOAT_CRASHES_FIRMWARE



#endif // _RP2040_EXPLORE__DEVELOPMENT_DEFINES
