#ifndef _ROUTINE_OPTIONS_H
#define _ROUTINE_OPTIONS_H


enum pulse_pro_routine_options
{
    MARK_START_OF_ROUTINE_OPTIONS,
    SHOW_ALL,
    SHOW_FIRST_AND_LAST,
    SUMMARY_CALLBACKS_ENABLED_FOR_FLAG_SET,
    SUMMARY_CALLBACKS_ENABLED_FOR_FLAG_CLEAR,
    SUMMARY_ALL_CALLBACKS_ENABLED,
    MARK_END_OF_ROUTINE_OPTIONS,
};


#endif // _ROUTINE_OPTIONS_H
